name: Passwall Test

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Target architecture"
        required: true
        default: x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false

      - name: Build package
        uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: ${{ github.event.inputs.arch }}-main
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/Openwrt-Passwall/openwrt-passwall-packages;main
            src-git|passwall_luci|https://github.com/Openwrt-Passwall/openwrt-passwall;main
            src-git|passwall2|https://github.com/Openwrt-Passwall/openwrt-passwall2;main
            src-git|peditx_themes|https://github.com/peditx/luci-theme-peditx^main
            src-git|peditx_carbon|https://github.com/peditx/luci-theme-carbonpx^main
            src-git|peditx_switch|https://github.com/peditx/luci-app-themeswitch^main
          KEY_BUILD: ${{ secrets.SIGN_PRIV_KEY }}
          PRIVATE_KEY: ${{ secrets.APK_PRIVATE_KEY }}
          V: s
          GOLANG_COMMIT: master

      - name: Save Build Result
        uses: actions/upload-artifact@v7
        with:
          name: openwrt-passwall-${{ github.event.inputs.arch }}
          path: bin/packages/${{ github.event.inputs.arch }}/passwall*/*
          retention-days: 7
