name: Test 5
on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Target architecture"
        required: true
        default: x86_64
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: echo "Architecture is ${{ github.event.inputs.arch }}"
      - name: Build package
        uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: ${{ github.event.inputs.arch }}-main
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/Openwrt-Passwall/openwrt-passwall-packages;main
          V: s
