name: Test 3
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: x86_64-main
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/Openwrt-Passwall/openwrt-passwall-packages;main
          V: s
