name: Test 2
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
      - name: Checkout
        uses: actions/checkout@v7
      - name: Test
        run: echo "Hello from Test 2!"
